### ISSUE TITLE
different results with different parameters

### ISSUE THREAD

**Issue by dongyangzheng** [hsinnan75/GSAlign#13]
Hi Professor:
      Did you ever test the different  parameters  influence on the results . 
    eg.  wheat versus rice  you know that wheat with large genome , and ABD
   is very similarity.  but when  adjust the parameters   found that the maf file can range from 
   4MB to 40MB ,   4MB  is not a good results.  hope you will give some advice on parameter select .
   I  think that the parameters  should not affect the results in a huge range. 
 Best regards

**Comment by hsinnan75** [comment]
Thank you for the information. Could you show me links for downloading the genome sequences? We'll test and debug on that dataset. Thank you!

**Comment by dongyangzheng** [comment]
> Thank you for the information. Could you show me links for downloading the genome sequences? We'll test and debug on that dataset. Thank you!
Professor all data can bed found here  
http://plants.ensembl.org/index.html  : bread wheat Chinese spring and  orza stavia Janponica
