### ISSUE TITLE
Segmentation fault on alignment

### ISSUE THREAD

**Issue by salanova-elliott** [hsinnan75/GSAlign#4]
Hello,

I'm running GenAlign v1.0.21 installed through Bioconda on a machine running Ubuntu18.04. I was trying to align some chloroplast genomes and around half have been successfully processed through GSAlign, but the others are producing a `Segmentation fault (core dumped)` error. I can't see any obvious differences between files that are working and those that aren't. Attached are two genomes that are producing the error.

[chloros.zip](https://github.com/hsinnan75/GSAlign/files/4649252/chloros.zip)

Any ideas on what could be causing the problem?

Thanks!

**Comment by hsinnan75** [comment]
Thank you for reporting this issue. I'll find the bugs with the two files and let you know asap.

**Comment by hsinnan75** [comment]
The headers of the two sequences are too long to load to memory. If you use a much shorter header, the error won't happen.

**Comment by salanova-elliott** [comment]
Great, thank you so much for the incredibly fast response time!

**Comment by yassineS** [comment]
Thanks for the great support!

I just wanted to note that this issue is resolved when working with fast, but persists when working with an indexed target (`-i`).
