### ISSUE TITLE
-one option

### ISSUE THREAD

**Issue by pjm43** [hsinnan75/GSAlign#5]
Hi,
Can you better explain the -one option.
Thank,
Jeff

**Comment by hsinnan75** [comment]
Hi, if the 'one' option is set, there will be no any nucleotide on query genome aligned to multiple positions on reference genome. GSAlign will only output the longer alignment and discard the short one if they overlaps.

**Comment by pjm43** [comment]
Thanks for the quick response.  

I did want to mention that I think the github README is wrong as it currently says to leave the defaults as is for intra-species comparisons:

`Please note, if the two genome sequences are intra-species, it is recommended to run GSAlign with default parameters. However, if they are inter-species, it is recommended to run GSAlign with '-clr 50 -alen 200.'`

However the current defaults are actually the recommended inter-species comparisons ('-clr 50 -alen 200') at least in v1.0.22:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/22619807/86943668-f7856a80-c103-11ea-9787-82b9046c3159.png">

Thanks for providing an excellent program!

**Comment by hsinnan75** [comment]
Thank you! I've removed the remark.
